// Copyright (C) 1991-2009 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.0 (Build Build 132 02/25/2009)
// Created on Mon Aug 03 17:33:37 2020

MultiplierPolynomial(scalar) MultiplierPolynomial(scalar)_inst
(
	.first(first_sig) ,	// input [319:0] first_sig
	.second(second_sig) ,	// input [31:0] second_sig
	.clk(clk_sig) ,	// input  clk_sig
	.output(output_sig) 	// output [319:0] output_sig
);

